---
title: "R Notebook"
output: html_notebook
---
```{r}
library(Giotto)
library(reticulate)
library(readr)
library(tidyverse)
```


```{r}

files = list.files("./../../output/", pattern = ".csv")
data_path = "./../../output/"
data_list = list()
p = 0

for (i in files){
  p = p+1
 data_list[[i]] <- readr::read_csv(paste0(data_path,i))
 data_list[[i]] = data_list[[i]] %>% select("label1", "label2", "PI_value")
 data_list[[i]]$label = paste(data_list[[i]]$label1, data_list[[i]]$label2, sep = "_")
 data_list[[i]]$group_by = names(data_list)[p]
}


```

Perform kmeans clustering

```{r}
out = do.call(rbind,data_list)

try = as.data.frame(out) %>% select(label, PI_value, group_by)

try = spread(try, key = label, value = PI_value)

library(ggplot2)
library(pheatmap)
library(caret)

rownames(try) = try$group_by
pheatmap(try[,-1], treeheight_row = 0, treeheight_col = 0)


pheatmap(try[,-1], kmeans_k = 3, treeheight_row = 0, treeheight_col = 0)

pheatmap(try[,-1], clustering_distance_rows="euclidean", clustering_method="median", 
         kmeans_k = 3, show_rownames=TRUE)

km <- kmeans(try[,-1], centers=3)
cluster_assignments <- km$cluster
result = cbind(try[,1],cluster_assignments)

label = rep(c("random","self_0.6", "self_0.4"), each=20)


table(result[,2], label)

result[,2][result[,2] == "2"] <- "random"
result[,2][result[,2] == "1"] <- "self_0.6"
result[,2][result[,2] == "3"] <- "self_0.4"

conf_mat = confusionMatrix(as.factor(as.vector(result[,2])), as.factor(label))
# look for accuraxy

```

Another rf model with cross-validation
```{r}
library(randomForestSRC)

sig_matrix <- as.matrix(try[,-1])
sig_matrix = sig_matrix[-c(1:20),]
labels <- rep(c("A","B"), each=20)

# Convert labels to a factor
labels <- as.factor(labels)

# Fit the model using k-fold cross-validation
cv_rf <- rfsrc(labels ~ ., 
               data = data.frame(sig_matrix, labels), 
               ntree = 500, 
               cv.fold = 10)

# Print the cross-validation results
cv_rf
```
heatmap

```{r}
try = as.data.frame(out) %>% select(label1, label2, PI_value, group_by)
 try$key = paste(try$label1, try$label2, sep = "_")
 try = try %>% select(-c(label1, label2))

 try = spread(try, key = key, value = PI_value)
 try = try[-c(41:60),]

 rownames(try) = try$group_by
 pheatmap(try[,-1], treeheight_row = 0, treeheight_col = 0)
```

